- docs/getting_help.md
- Change link point to git-scm.com instead of GitHub
Improve link by pointing it directly at the place where you can read the book.
> Change link point to git-scm.com instead of GitHub

- docs/abbreviations.md
- changed the abbreviation for 'IDE' from 'Integrated Development Editor' to 'Integrated Development Environment'.
'IDE' stands for 'Integrated Development Environment', which *includes* an editor.
see https://en.wikipedia.org/wiki/Integrated_development_environment
> change 'Editor' to 'Environment' for 'IDE'.

- .github/workflows/node.js.yml
- Update workflow comment to reflect current configuration
- Add name to `npm install -g yarn` step
- Improve name for Yarn install + build step
- Add white space around steps.
> Improve GitHub Action

- .github/workflows/node.js.yml
- Bump `actions/checkout` to latest v2.3.3 release
We should use the latest versions of the GitHub action runners.
> Bump actions/checkout to v2.3.3

- renovate.json
- Manually group Docusaurus monorepo packages in the Renovate bot config file.
Thank you Rhys Arkins for providing me with the improved config!
For now I need to manually group the Docusaurus packages.
This is because the Docusaurus monorepo package.json files have incomplete repository/directory metadata.
Fixes #53
Co-authored-by: Rhys Arkins <rhys@arkins.net>
> Group Docusaurus monorepo packages

- docs/contribute_to_a_project_by_forking.md
- sidebars.js
- Create section Contribute to a project by forking
Fixes #24
> Create section Contribute to a project by forking

- docs/advanced_topics/use_git_bisect_to_find_bugs.md
- sidebars.js
- Create new section that covers `git bisect`
Fixes #75
> docs: create section covering git bisect

- package.json
- yarn.lock
- Use a Yarn resolution to pin `@mdx-js/react` to `1.6.19` because newer versions break the syntax highlighting.
- Do a manual `yarn upgrade` run to upgrade the other dependencies.
> chore(deps): pin @mdx-js/react to 1.6.19 and do manual lock file maintenance

- package.json
- yarn.lock
- Remove resolution blocking @mdx-js/react from upgrading
- Pin @mdx-js/react to 1.6.21
- Do a yarn upgrade to upgrade the lockfile
> chore(deps): upgrade @mdx-js/react to 1.6.21 manually

- .prettierignore
- renovate.json
- Ignore the Docusaurus canary builds with a regex
This should help to ignore the unwanted Docusaurus canary builds.
> ci: ignore Docusaurus canary builds

- .github/workflows/node.js.yml
- Ensure that npm actually makes a Docusaurus build
> ci: fix docusaurus build not running

- CONTRIBUTING.md
- README.md
- docusaurus.config.js
- package-lock.json
- package.json
- src/css/custom.css
- Remove darkmode toggle
- Specify default Prism theme that we use to highlight code blocks
- Add announcement on top of page on first load (dismissable)
- Throw when we encounter a duplicate rout, or a broken Markdown link
- Remove `lint-fix` command and use `prettier-fix` instead
- Use a more contrasting basic color scheme
- Lock file maintenance
> Improvements

- README.md
- package.json
- Add new `after-upgrade` command to clear cache after docusaurus upgrade
- Use proper syntax highlighting in README.md
No issue is fixed with this.
> create after-upgrade command, fix syntax highlighting

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- .github/workflows/node.js.yml
- .github/workflows/prettier.yml
- Simplify repository templates
- Improve CI step and job names
> chore: improve CI step/job names, simplify repo templates

- .github/workflows/docusaurus-build.yml
- README.md
- Use `Docusaurus build` as name instead of `Node.js CI`
- Update test status badge in `README.md`
> chore: use better CI name, update README badge

- package-lock.json
- package.json
- Update Docusaurus monorepo to pinned release of `canary` branch
- Update React to `17.0.1`
Docusaurus just released a `canary` release that supports React 17.
> fix(deps): update docusaurus monorepo, update react

- docs/advanced_topics/advanced_git_configuration.md
- docs/advanced_topics/clean_up_your_git_history.md
- docs/advanced_topics/contribute_to_a_project_by_forking.md
- docs/best_practices/split_up_your_commits.md
- docs/best_practices/testing_and_github_actions.md
- docs/best_practices/use_a_dependency_bot.md
- docs/best_practices/write_good_commit_messages.md
- docs/further_resources/recommended_reading.md
- docs/getting_started/configuring_git.md
- docs/getting_started/conventions.md
- docs/getting_started/create_a_github_account.md
- docs/getting_started/installing_git.md
- docs/git_sandbox/add_extra_lines_to_file.md
- docs/git_sandbox/check_the_repository_history_with_git_log.md
- docs/git_sandbox/create_a_new_branch.md
- docs/git_sandbox/create_your_first_github_repo.md
- docs/git_sandbox/editing_a_file_on_github.md
- docs/git_sandbox/explore_your_git_sandbox.md
- docs/git_sandbox/fetching_changes_merging_git_pull.md
- docs/git_sandbox/introduction_to_git_status.md
- docs/git_sandbox/merge_pull_request.md
- docs/git_sandbox/setup_your_git_sandbox.md
- docs/git_sandbox/switching_between_branches.md
- docs/git_sandbox/your_first_merge.md
- docs/the_nano_text_editor/introduction_to_the_nano_text_editor.md
- Improve admonitions (remove some, add titles to others)
- Tell readers to use GitHub provided `no-reply` email address
I was using too many admonitions, so I've dropped some. 😄 
I'm also fixing some small textual errors that I noticed along the way.
> docs: improve admonitions and fix some small stuff

- package-lock.json
- package.json
- Bump to latest `@canary` release for Docusaurus v2 monorepo
Get some package updates.
> fix(deps): update docusaurus monorepo

- docs/getting_started/list_of_abbreviations.md
- docs/git_sandbox/setup_your_git_sandbox.md
- Clarify why Bash shell commands won't work properly
- Explain that macOS terminal defaults to the Z shell
Reminder: fixup abbreviations section to mention Z Shell as well.
> docs: update Bash command caution

- package-lock.json
- package.json
- Bump Docusaurus v2 to alpha.71
- Lockfile maintainance
Upgrade project dependencies.
> fix(deps): update docusaurus monorepo and lockfile

- .github/contributing.md
- README.md
- Create `contributing.md` file
- Link to `contributing.md` from README
- Improve some sentences
General cleanup of the README.
> chore: create contributing.md

- docs/getting_started/create_a_github_account.md
- Improve URLs linking to GitHub docs
> docs: improve URLs linking to GitHub docs

- docs/advanced_topics/contribute_to_a_project_by_forking.md
- docs/best_practices/use_a_dependency_bot.md
- docs/further_resources/recommended_reading.md
- docs/getting_started/configuring_git.md
- docs/getting_started/create_a_github_account.md
- docs/git_sandbox/create_your_first_github_repo.md
- Fix up the links to the GitHub docs
- Standardize verbiage in links to GitHub docs
- Improve sentences with the links a bit
Further work based on PR #204.
> docs: improve links to GitHub docs

- docs/further_resources/recommended_reading.md
> docs: improve recommended reading section

- package-lock.json
- package.json
- Update `@docusaurus/core` to `ce0764033`
- Update `@docusaurus/preset-classic` to `ce0764033`
This gets me some documentation styling fixes and fixes for security vulnerabilities in dependencies.
> fix(deps): update docusaurus monorepo to ce0764033

- docs/advanced_topics/advanced_git_configuration.md
- Improve sentences
- Remove reference to "later on GitHub will use `main` as default", as Github now uses `main` as default
General updates/cleanup of this section.
> docs: update advanced Git configuration section

- docs/further_resources/recommended_reading.md
- Improve sentences
General clean-up of text in this section.
> docs: update Recommended reading section

- docs/best_practices/use_a_dependency_bot.md
- Improve sentences
- Use emoji check-marks in table
General cleanup/updating of section.
> docs: improve Use a dependency bot section

- package-lock.json
- package.json
- Grab latest Docusaurus monorepo packages
> fix(deps): update docusaurus monorepo to 0bbbfb641

- package-lock.json
- package.json
- Update docusaurus monorepo to v2.0.0-beta.1
Use latest stable release.
> fix(deps): update docusaurus monorepo to v2.0.0-beta.1

- renovate.json
- Automerge Docusaurus stable packages
- Automerge Prettier packages
- Automerge minor/patch React monorepo updates
Let's try automating some more package updates.
> ci: automerge more packages with Renovate bot

- .github/workflows/docusaurus-build.yml
- .github/workflows/prettier.yml
- Enable the built-in npm package cache
Should speed up the tests/builds.
> ci: enable npm cache

- vercel.json
- Stop Vercel for GitHub bot/integration from commenting on PRs/comments
Let's try this config, and see how we get on.
> chore: make Vercel for GitHub integration silent

- docs/about_this_guide/guide_introduction.md
- docs/advanced_topics/working_with_large_files.md
- docs/further_resources/recommended_reading.md
- docs/git_basics/short_introduction_to_git.md
- sidebars.js
- Create new section `Git basics` with a `Introduction to Git` file
- Create new file `Working with large files` under the `Advanced topics` section
- Adjust sidebar to account for new sections
- Explain who should learn Git in the guide introduction
- Explain what kinds of files you should track with Git
- Link to Git LFS limitations wiki
Just some general improvements. Not fixing an issue with this PR.
> docs: new sections Git basics, Working with large files

- .github/workflows/docusaurus-build.yml
- .github/workflows/prettier.yml
- Set explicit permissions for the workflow files
We should be explicit in the permissions we grant to the action.
Use the principle of least privilege.
> ci: restrict GitHub Action permissions

- docs/getting_started/installing_git.md
- Mention Debian backports repository
Mention that Debian users can use the backports repo to grab a newer version of Git than the one that comes with the default repositories.
> docs: mention Debian backports repository

- docs/best_practices/use_a_gitignore_file.md
- Use better heading titles
- Rewrite some sentences for clarity
- Better explain where a link will take the reader
> docs: improve Gitignore section

- renovate.json
- Remove Docusaurus special handling in `renovate.json`
Let's see what the default Renovate settings get me now that the dist-tags are cleaner up.
> chore: remove docusaurus special handling

- package-lock.json
- package.json
- Revert to Docusaurus beta 3
Let's see if Renovate picks up the correct version of Docusaurus to upgrade to now (should be 4).
> chore: revert to docusaurus beta 3

- package-lock.json
- package.json
- Use Docusaurus canary releases
Let's see what happens with no extra Renovate config.
> chore: use docusaurus canary releases

- renovate.json
- Remove `supportPolicy` as it's going to be removed from Renovate in `v26` anyways
> chore: remove supportPolicy node object

- .gitpod.yml
- Add prepare step to Gitpod startup
> chore: add prepare step to Gitpod startup

- .gitpod.yml
Improve Gitpod configuration:
- Run `mkdocs serve` after startup
- Run default `make` command
> chore: improve Gitpod configuration

- README.md
- Add Prettier badge to readme
> chore: add Prettier badge to readme

- renovate.json
- Automerge `patch` updates for `mkdocs` and `mkdocs-material`
Reduce manual work.
> chore: automerge patch level mkdocs and mkdocs-material updates

- mkdocs.yml
- Add dark mode
- Follow user's color mode preference
- Add toggle to switch between light/dark mode
Add dark mode.
> chore: add dark mode

- .github/workflows/dependency-review.yml
- Use dependency review action
Helps avoid dependency update PRs that have vulnerabilities in them.
[GitHub docs, Dependency review enforcement](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement)
Project: [`actions/dependency-review-action`](https://github.com/actions/dependency-review-action).
> chore: use dependency review action

- .github/contributing.md
- .github/workflows/prettier.yml
- .gitpod.yml
- package.json
- Update node.js to 16
Updating to latest Node LTS.
> chore: update node.js to 16

- .github/workflows/dependency-review.yml
- Pin GitHub Action digests
Makes Renovate follow the correct tags in future updates.
> chore: pin GitHub Action digests

- package.json
- Enable Prettier's `--cache` option to speed up runs
Speed up repeated runs of Prettier on the same machine.
> chore: enable Prettier cache

- LICENSE.md
- drop reference to deleted folder
This is a left over from the time I still used Docusaurus 2.
> docs(license): drop reference to deleted folder

- renovate.json
- Enable config migration for Renovate bot
Renovate can update it's own configuration file for us.
> chore: enable config migration for Renovate

- docs/getting_started/create_a_github_account.md
- Mention GitHub requires 2FA at the end of 2023
- Update links to GitHub Docs
- Drop list of 2FA methods, and let the reader refer to the list of 2FA methods in the GitHub Docs
- Drop references to SMS authentication
Just updating the page.
> docs(create a github account): update page

- .github/contributing.md
- README.md
- docs/advanced_topics/clean_up_your_git_history.md
- docs/advanced_topics/contribute_to_a_project_by_forking.md
- docs/git_sandbox/create_your_first_github_repo.md
- docs/git_sandbox/editing_a_file_on_github.md
- docs/git_sandbox/making_your_first_commit.md
- docs/git_sandbox/merge_pull_request.md
- docs/git_sandbox/shell_expansion.md
- docs/recommendations/git_aliases.md
- docs/recommendations/testing_and_github_actions.md
- Use input-neutral language
Replace verbs like `click` and `type` with input-neutral verbs.
> docs: use input-neutral language

- .github/contributing.md
- .github/workflows/prettier.yml
- .gitpod.yml
- package-lock.json
> chore: update to node 18

- mkdocs.yml
- Drop the source code button
If anybody wants to contribute, they'll probably want to edit the source. Having two buttons increases the chance a user selects the wrong button.
> chore: drop source code view button

- docs/recommendations/use_a_dependency_bot.md
- Remove word `bot` after `Renovate`
- Update some links
Drive by PR, not closing any issue with this.
> docs: update use a dependency bot page

- mkdocs.yml
- requirements.txt
- Use new navigation pruning feature to reduce the size of the HTML build
- Drop polyfills for ancient browsers
Let's try this update.
> chore(deps): update dependency mkdocs-material to v9.2.0b0

- mkdocs.yml
- requirements.txt
Reverts HonkingGoose/git-gosling#554
> Revert "chore(deps): update dependency mkdocs-material to v9.2.0b0"

- docs/getting_started/installing_git.md
- Drop references to old Ubuntu LTS versions
- Use simple words and phrases
- Use better link name
- Use input-neutral language
Some improvements.
> docs: update installing Git instructions

- renovate.json
- Replace `config:base` with `config:best-practices`
- Drop `helpers:pinGitHubActionDigests` because it's included in `config:best-practices`
Opt-in to Renovate maintainer's best practices preset.
> chore: replace config:base with config:best-practices

- renovate.json
- Drop my own `configMigration=true` because it's included in `config:best-practices`
> chore: config:best-practices includes config migration

- .github/contributing.md
- .github/workflows/prettier.yml
- .gitpod.yml
- package-lock.json
- Update to Node.js 20
Use latest Node.js LTS version.
> chore: update to Node.js 20

- mkdocs.yml
- Follow MkDocs maintainers recommended link check strictness [^1]
> Recommended settings for most sites (maximal strictness):
> 
> ```yaml
> validation:
>   omitted_files: warn
>   absolute_links: warn
>   unrecognized_links: warn
> ```
[^1]: https://www.mkdocs.org/user-guide/configuration/#validation
> chore: recommended strictness for link checks

- .github/dependabot.yml
- Get Dependabot PRs
See the difference in changelog formats between Dependabot and Renovate.
> chore: try Dependabot

- docs/git_sandbox/create_your_first_github_repo.md
- Some small style fixes
Drive by PR.
> docs: style fixes

- docs/getting_started/installing_git.md
- Capitalize abbreviation PPA
Drive by PR.
> docs: capitalize abbreviation PPA

- includes/abbreviations.md
- Add abbrevation `PPA` to list of abbreviations
The docs site will show a explanation of the abbreviation when you hover over it with your input device.
> docs: add PPA to list of abbreviations

- mkdocs.yml
- Configure automatic light/dark mode
- Watch the `includes` directory so the site preview updates when you edit the `abbrevations.md` file 
Improve the Material for MkDocs configuration.
> chore: improve Material for MkDocs config

- .github/workflows/dependency-review.yml
- .github/workflows/prettier.yml
- .husky/pre-commit
- package.json
- Migrate to Husky v9 style config
- Don't install Husky in GitHub Actions environment.
Follow-up after:
- #636
> chore: migrate to husky v9 style config

- .github/workflows/prettier.yml
- Upgrade the version of Node.js used in the Prettier workflow
Node.js 22 is the latest version.
> chore: update version of Node.js for Prettier workflow
